name: Discord Notification for Pull Requests

on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
    - name: Send Discord notification
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
          "username": "GitHub PR Bot",
          "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
          "content": "",
          "embeds": [{
            "title": "🔔 Nouvelle Pull Request #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}",
            "description": "${{ github.event.pull_request.body || 'Pas de description fournie.' }}",
            "url": "${{ github.event.pull_request.html_url }}",
            "color": ${{
              github.event.action == 'opened' ? 3066993 : github.event.action == 'closed' ? 15158332 : 15844367
            }},
            "fields": [
              {
                "name": "Auteur",
                "value": "[${{ github.event.pull_request.user.login }}](${{ github.event.pull_request.user.html_url }})",
                "inline": true
              },
              {
                "name": "État",
                "value": "${{ github.event.pull_request.state == 'open' ? 'Ouvert' : 'Fermé' }}",
                "inline": true
              },
              {
                "name": "Mergeable",
                "value": "${{ github.event.pull_request.mergeable != null ? (github.event.pull_request.mergeable ? 'Oui' : 'Non') : 'Non défini' }}",
                "inline": true
              }
            ],
            "footer": {
              "text": "Dépôt: ${{ github.repository.name }} | PR Créée à",
              "icon_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
            },
            "timestamp": "${{ github.event.pull_request.created_at }}"
          }]
        }' \
        ${{ secrets.DISCORD_WEBHOOK_URL }}
